import type { Metadata } from "next";
import "./globals.css";
import LayoutComponent from "./_components/LayoutComponent";

import '@radix-ui/themes/styles.css';
import { Theme } from "@radix-ui/themes";
import { ConfigProvider } from "antd";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const optionsConfigs =
  {
    components:{
      Input:{
        hoverBorderColor:"#4361EE",
        activeBorderColor:"#4361EE"
      },
      DatePicker:{
        hoverBorderColor:"#4361EE",
        activeBorderColor:"#4361EE"
      }
    }
  }

  return (
    <html lang="en">
      <body>
        <Theme>
          <ConfigProvider theme={optionsConfigs}>
            <LayoutComponent >
              {children}
            </LayoutComponent>
          </ConfigProvider>
        </Theme>
      </body>
    </html>
  );
}
